name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package & dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        pip install -e .
        pip install ruff pytest coverage pytest-cov
        pip list

    - name: Run linting
      run: ruff check src/ tests/

    - name: Run Tests
      timeout-minutes: 5
      run: |
        python -m pytest --cov=ghweekly src/ tests/ -v -s

    - name: Statistics
      run: |
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
