name: Daily Update Weekly Commits

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  update-weekly-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package in editable mode
      run: pip install -e .

    - name: Run script to update weekly commits
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python scripts/plot_commits.py

    - name: Commit and push updated image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/bhimrazy/gh-weekly-commits.git
        git add .
        git commit -m "Update weekly commits image" || echo "No changes to commit"
        git push origin main
